# Example hooks configuration for Codex
# This demonstrates how to configure Stop hooks that execute when sessions complete

[hooks.stop.session-notify]
command = "$CODEX_PROJECT_DIR/.codex/hooks/strategic/stop-session-notify.py"
timeout_ms = 30000
enabled = true
